sonar.organization=lucianodato
sonar.projectKey=lucianodato_noise-repellent
sonar.sources=Source/PluginEditor.cpp,Source/PluginEditor.h,Source/PluginProcessor.cpp,Source/PluginProcessor.h,Source/GUI
sonar.tests=Source/Tests
sonar.cfamily.compile-commands=build-test/compile_commands.json
sonar.cfamily.cobertura.reportPaths=build-test/coverage.xml
