#!/bin/bash

# Clean
rm -rf build /tmp/nrepel.lv2 || true

# Build now
meson build --buildtype release --prefix /tmp
ninja -v -C build
ninja -C build install

# Compress build in a zip file
zip -9 -r noise-repellent.zip /tmp/nrepel.lv2