#!/bin/bash

# Clean
rm -rf build nrepel.lv2 || true

# Build now
meson build --buildtype release
cd build
ninja -v

# Move needed sources to bin folder
cd .. && mkdir -p nrepel.lv2
cp build/nrepel.dll ./nrepel.lv2
cp build/manifest.ttl ./nrepel.lv2
cp lv2ttl/nrepel.ttl ./nrepel.lv2

# Compress build in a zip file
zip -9 -r noise-repellent-win.zip ./nrepel.lv2/