#!/bin/bash

# Clean
rm -rf build /tmp/nrepel.lv2 || true

# Build now
meson build --buildtype release --prefix /tmp
ninja -v -C build
ninja -C build install

# Compress build in a zip file
mv /tmp/nrepel.lv2 ./nrepel.lv2
zip -9 -r noise-repellent.zip ./nrepel.lv2